#!/bin/bash
# Linux Setup Script (LSS)
# Author: iseijin
# Date: 13/05/2013
# Description: Use git to retrieve various Linux Configuration files from a repository on github.
#+++++++++++++++++++++
#       ~/.bashrc
#       ~/.bash_aliases
#       ~/.vimrc
#       ~/.Xresources
#       ~/.vim/
#+++++++++++++++++++++
# This script runs from ~/bin - create the directory if it doesn't exist or modify the file to reflect where you want your scripts folder e.g. ~/scripts, /usr/bin

if eval "ping -c 1 www.google.com > /dev/null"; then
  :
else
  echo "I require an internet connection but cannot find one. Aborting."
  exit 1
fi

# Test if git is installed
command -v git >/dev/null 2>&1 || { echo >&2 "I require git but it's not installed.  Aborting."; exit 1;  }

# Verify repo exists
cd ~/bin/LSS && git show-ref > /dev/null
verify=$?
directory="/home/$USER/bin/LSS/lss"
if [ $verify -eq 0 ]; then
  echo "The LSS git already exists, continuing..."
  self_delete=false
  if [ $0 != $directory ]; then # Delete this copy of the script is not part of the repo (providing a copy of the repo is found)
    self_delete=true
  fi
else  
  self_delete=true # Delete this file as the real copy will be retrieved with git
  printf "This script cannot be run without the Git repo, the following command will be run first:\ngit clone git@github.com:iseijin/LSS.git ~/bin/LSS"
  git clone git@github.com:iseijin/LSS.git ~/bin/LSS
fi

# Create sym links to files in LSS/configFiles
FILES=".bashrc
.bash_aliases
.vimrc
.Xresources
.vim
"

for f in $FILES
do
  testname=$f
  backup=$testname.backup
  fullpath=$HOME/$testname
  if [ ! -L $fullpath ] && [ -e $fullpath ]; then # Backup if it is a FILE and NOT a link
    if [ -e $HOME/$backup ]; then
      i=2
      while [ -e $HOME/$backup$i ]; do
        let i++
      done
      name=$backup$i
    fi
    echo "Backing up $testpath to $HOME/$backup"
    mv $testpath $HOME/$backup
    echo "Creating link for $fullpath"
    ln -s $fpath/bin/LSS/configFiles/$testname $fullpath
  elif [ -L $fullpath ]; then
    # If file is a LINK
    target=`readlink $fullpath`
    if [ $target != $fpath/bin/LSS/configFiles/$testname ]; then
      echo "Creating link for $fullpath"
      ln -sf $fpath/bin/LSS/configFiles/$testname $fullpath
    else
      echo "Link for $fullpath has already been created."
    fi
  fi
done

if [ -e ~/.bashrc ]; then
  source ~/.bashrc
fi

if $self_delete ; then
  echo "Deleting $0"
  rm $0
fi
