#!/bin/bash
# Linux Setup Script (LSS)
# Author: iseijin
# Date: 13/05/2013
# Description: Use git to retrieve various Linux Configuration files from a repository on github.
#+++++++++++++++++++++
# Files:
#       .bashrc
#       .bash_aliases
#       .vimrc
#       .Xresources
# Dirs:
#       ~/.vim/
#+++++++++++++++++++++
# This script runs from ~/bin - create the directory if it doesn't exist or modify the file to reflect where you want your scripts folder e.g. ~/scripts, /usr/bin

# Exit if the repo doesn't exist.
# git verify command here
if [ $? -eq 0 ]; then
  echo "The LSS git already exists, skipping this part."
else
  printf "Cannot be run in this fashion run the following command first:\ngit clone git@github.com:iseijin/LSS.git ~/bin/LSS"
  exit 32
fi

# Create sym links to files in LSS/configFiles
if [ ! -L ~/.bashrc ]; then
  echo "Creating link for ~/.bashrc"
  ln -s ~/bin/LSS/configFiles/.bashrc ~/.bashrc
fi

if [ ! -L ~/.bash_aliases ]; then
  echo "Creating link for ~/.bash_aliases"
  ln -s ~/bin/LSS/configFiles/.bash_aliases ~/.bash_aliases
fi

if [ ! -L ~/.vimrc ]; then
  echo "Creating link for ~/.vimrc"
  ln -s ~/bin/LSS/configFiles/.vimrc ~/.vimrc
fi

if [ ! -L ~/.Xresources ]; then
  echo "Creating link for ~/.Xresources"
  ln -s ~/bin/LSS/configFiles/.Xresources ~/.Xresources
fi

if [ ! -L ~/.vim ]; then
  echo "Creating link for ~/.vim"
  ln -s ~/bin/LSS/configFiles/.vim ~/.vim
fi
